### ISSUE TITLE
Returning flow identifiers

### ISSUE THREAD

**Issue by martinthomson** [DavidSchinazi/draft-h3-datagram#10]
There is a certain advantage to being able to use small flow identifiers, but there are only 32 of the smallest available for any given usage.  Would it be possible for a particular usage to reuse a value?

I ask because CONNECT-UDP has a distinct start and end and could possibly take advantage of this.  That would have some small, but likely meaningful, impact on efficiency.

**Comment by DavidSchinazi** [comment]
I agree, this feature might make a real performance difference. The only caveat is reordering, we'll have to be careful that if receiving a RESET_STREAM frame for the CONNECT-UDP stream makes a flow ID available and a datagram with that flow ID gets reordered to arrive after, we'll need to check the packet number to make sure that this datagram is dropped instead of routed to its new owner.

**Comment by martinthomson** [comment]
I don't like looking at packet numbers and would be opposed to that.  It's a pretty serious layering violation.

A guard interval to minimize the potential for overlap might help, but I would prefer that we only allow reuse if the protocol that is carried has some sort of protection against receiving bad packets.  Tunneled QUIC should work fine for that (though Version Negotiation packets are still a little bit of a concern), as would tunneled STUN/TURN and WebRTC.

More analysis would be required if the protocol did not provide its own integrity protection, but as this is primarily a tunneling protocol, we might be safe in advising against that.
