### ISSUE TITLE
Running out of Flow IDs

### ISSUE THREAD

**Issue by LPardue** [DavidSchinazi/draft-h3-datagram#13]
https://tools.ietf.org/html/draft-schinazi-masque-h3-datagram-01#section-6 states:

```
   Note that integer structured fields can only encode values up to
   10^15-1, therefore the maximum possible value of the "Datagram-Flow-
   Id" header is lower then the theoretical maximum value of a flow
   identifier which is 2^62-1 due to the QUIC variable length integer
   encoding.  If the flow identifier allocation service of an endpoint
   runs out of values lower than 10^15-1, the endpoint MUST treat is as
   a connection error of type H3_ID_ERROR.
```

The text is a little ambiguous. I presume the intention is that the endpoint that is allocating flows should do what HTTP/3 defines as [Immediate Application Closure](https://tools.ietf.org/html/draft-ietf-quic-http-32#section-5.3)? The doesn't cover the case where an endpoint receives a Datagram Flow ID greater than 10^15-1 (either in a request or a DATAGRAM).

I think it might help to separate these cases. Receiving a value of 10^15-1 is always a connection error of type H3_ID_ERROR. 
But I'm not so sure about the sender case, if you really are flow ID exhausted, perhaps it is nicer to just spin up a new connection and leave the current one as is. We might recommend that endpoints initiate an HTTP/3 graceful close followed by an application close - but reusing H3_ID_ERROR for that case seems a bit overkill.

**Comment by DavidSchinazi** [comment]
I don't think receiving a DATAGRAM whose flow ID is >= 10^15 is an error, the receiver should just silently drop it as the flow ID is unknown. Either way we should add text to clarify the expected action of the receiver.

In the sender case, I agree with you when the sender is the client, because in that case the client should instead just spin up a separate connection. On the server sender however, there is no such escape hatch, so perhaps we should tell the server to fail the operation that requested the flow ID.

**Comment by LPardue** [comment]
Sorry I was not specific in my comment. I meant to speak about receiving the header field e.g.

```
Datagram-Flow-Id: 10000000000000000
```

That would lead to an SF Integer parsing error, which [IIUC](https://tools.ietf.org/html/draft-ietf-httpbis-header-structure-19) would cause the field to be ignored - unless we define different behaviour.

Ignoring the header has an interesting interplay with the optional guidance to `buffer it until they receive
   the "Datagram-Flow-Id" header`.

Ignoring things that are strictly above the known limits seems a little too generous. Is there a reason not to reject such requests and HTTP/3 DATAGRAMS?

**Comment by DavidSchinazi** [comment]
Ah, in that case I agree - receipt of a Datagram-Flow-Id header with value >= 10^15 should cause a connection error of type H3_ID_ERROR.

I was just thinking that conceptually receiving DATAGRAM with strange flow IDs should not be an error because that might lead implementors to declare than any unknown flow ID is an error which would break valid scenarios in the presence of reordering.

**Comment by LPardue** [comment]
Yeah. However, I think it would be fine to reject such a request with an 4xx response rather than tear down the entire connection...

**Comment by DavidSchinazi** [comment]
Fair enough, that works too. I'll just state that in that scenario the request is malformed
